POST  http://localhost:3001/api/users 
Content-Type: application/json

{
  "username": "eselva92",
  "name": "Eric",
  "password": "contraseña_eric"
}
 
###

POST  http://localhost:3001/api/users
Content-Type: application/json

{
}
