GET http://localhost:3001/api/notes/61f020f84d509132116579ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWZhYzUwZmY0OGVlN2EyZDAwNWNmNCIsInVzZXJuYW1lIjoiZXJpY3Rlc3QiLCJpYXQiOjE2NDMxMjU3NjksImV4cCI6MTY0MzczMDU2OX0.MncHCKT44qloeCPV-rsDJyAsyrVxENELWbjVoXqdWQM