POST  http://localhost:3001/api/notes 
Content-Type: application/json

{
  "content": "Test note from vcode request",
  "important": true,
  "userId": "61efac50ff48ee7a2d005cf4"
}
 
###

POST  http://localhost:3001/api/notes 
Content-Type: application/json

{
}
